// One-off generator: reads the real PRODUCTS export (full catalog data,
// including descriptions/specs/images) and writes out a trimmed
// src/data/products-lite.ts containing only { id, category, title } for
// each product — the only fields ReviewForm.jsx's inquiry-panel product
// picker actually reads. Run with: npx tsx scripts/gen-products-lite.ts
import { writeFileSync } from "node:fs";
import { PRODUCTS } from "../src/data/products.ts";

const lite = PRODUCTS.map((p) => ({
  id: p.id,
  category: p.category,
  title: p.title,
}));

const header = `// src/data/products-lite.ts
// AUTO-GENERATED by scripts/gen-products-lite.ts — do not hand-edit.
// Regenerate with: npx tsx scripts/gen-products-lite.ts
//
// Intentionally does NOT import from ./products.ts or ./products/*.ts.
// Those files bundle full descriptions, spec objects, feature lists, and
// image filenames for every product — fine for product pages, but far
// more than the inquiry-form product picker needs. This file exists so
// that picker (used by ExitIntentReviewPopup and as ReviewForm's inquiry
// fallback) doesn't drag ~380KB of unrelated catalog data into its JS
// bundle just to populate a category/title dropdown.
//
// If you add/rename/remove a product in src/data/products/*.ts, rerun
// the generator so this file stays in sync.

export interface ProductLite {
  id: string;
  category: string;
  title: string;
}

export const PRODUCTS_LITE: ProductLite[] = `;

const body = JSON.stringify(lite, null, 2);

writeFileSync(
  new URL("../src/data/products-lite.ts", import.meta.url),
  header + body + ";\n",
);

console.log(`Wrote ${lite.length} lite product entries to src/data/products-lite.ts`);
