// src/data/products-lite.ts
// AUTO-GENERATED by scripts/gen-products-lite.ts — do not hand-edit.
// Regenerate with: npx tsx scripts/gen-products-lite.ts
//
// Intentionally does NOT import from ./products.ts or ./products/*.ts.
// Those files bundle full descriptions, spec objects, feature lists, and
// image filenames for every product — fine for product pages, but far
// more than the inquiry-form product picker needs. This file exists so
// that picker (used by ExitIntentReviewPopup and as ReviewForm's inquiry
// fallback) doesn't drag ~380KB of unrelated catalog data into its JS
// bundle just to populate a category/title dropdown.
//
// If you add/rename/remove a product in src/data/products/*.ts, rerun
// the generator so this file stays in sync.

export interface ProductLite {
  id: string;
  category: string;
  title: string;
}

export const PRODUCTS_LITE: ProductLite[] = [
  {
    "id": "prod_f1",
    "category": "Industrial Filtration",
    "title": "Triveni Replacement Turbine Lube Oil Filter Elements"
  },
  {
    "id": "prod_f2",
    "category": "Industrial Filtration",
    "title": "Siemens Replacement Turbine Lube Oil Filter Elements"
  },
  {
    "id": "prod_f3",
    "category": "Industrial Filtration",
    "title": "SS Wire Mesh (CEP) Centrifugal Filter Elements"
  },
  {
    "id": "prod_f4",
    "category": "Industrial Filtration",
    "title": "Tank Breather Filter Elements (NBF Series)"
  },
  {
    "id": "prod_f5",
    "category": "Industrial Filtration",
    "title": "Hydraulic Suction Strainer Elements (AS/TS Series)"
  },
  {
    "id": "prod_f6",
    "category": "Industrial Filtration",
    "title": "WaterSorp Offline Filter Elements (WSNR Series)"
  },
  {
    "id": "prod_f7",
    "category": "Industrial Filtration",
    "title": "PTFE Hydrophobic Air & Gas Filter Elements"
  },
  {
    "id": "prod_f8",
    "category": "Industrial Filtration",
    "title": "Return-Line Filter Elements"
  },
  {
    "id": "prod_f9",
    "category": "Industrial Filtration",
    "title": "Duplex Control Oil Filter Assembly"
  },
  {
    "id": "prod_f10",
    "category": "Industrial Filtration",
    "title": "Duplex Fabricated Filter Housing"
  },
  {
    "id": "prod_st1",
    "category": "Industrial Strainers",
    "title": "Simplex Basket Strainer"
  },
  {
    "id": "prod_st2",
    "category": "Industrial Strainers",
    "title": "Duplex Basket Strainer"
  },
  {
    "id": "prod_st3",
    "category": "Industrial Strainers",
    "title": "Conical Strainer"
  },
  {
    "id": "prod_st4",
    "category": "Industrial Strainers",
    "title": "Y-Type Strainer"
  },
  {
    "id": "prod_st5",
    "category": "Industrial Strainers",
    "title": "Pot / Bucket Type Strainer"
  },
  {
    "id": "prod_st5b",
    "category": "Industrial Strainers",
    "title": "Basket Strainer Elements"
  },
  {
    "id": "prod_e1",
    "category": "Expansion Joints",
    "title": "Stainless Steel Metallic Bellows Expansion Joint"
  },
  {
    "id": "prod_e1b",
    "category": "Expansion Joints",
    "title": "Axial Expansion Joint"
  },
  {
    "id": "prod_e2",
    "category": "Expansion Joints",
    "title": "Double Arch Rubber Expansion Joint"
  },
  {
    "id": "prod_e3",
    "category": "Expansion Joints",
    "title": "Single Arch Rubber Expansion Joint"
  },
  {
    "id": "prod_e3b",
    "category": "Expansion Joints",
    "title": "Wide Arch Rubber Expansion Bellow"
  },
  {
    "id": "prod_e3c",
    "category": "Expansion Joints",
    "title": "Industrial Heat Exchanger Bellows"
  },
  {
    "id": "prod_e4",
    "category": "Expansion Joints",
    "title": "Universal Metallic Expansion Joint"
  },
  {
    "id": "prod_e5",
    "category": "Expansion Joints",
    "title": "Non-Metallic Fabric Expansion Joint"
  },
  {
    "id": "prod_e6",
    "category": "Expansion Joints",
    "title": "Pressure Balance Expansion Joint"
  },
  {
    "id": "prod_e7",
    "category": "Expansion Joints",
    "title": "Ring Reinforced Metallic Expansion Joint"
  },
  {
    "id": "prod_e9",
    "category": "Expansion Joints",
    "title": "Lateral Metallic Expansion Joint"
  },
  {
    "id": "prod_e10",
    "category": "Expansion Joints",
    "title": "Angular Hinged / Gimbal Expansion Joint"
  },
  {
    "id": "prod_e11",
    "category": "Expansion Joints",
    "title": "Metallic Vibration Absorber"
  },
  {
    "id": "prod_e13",
    "category": "Expansion Joints",
    "title": "Steam Crossover Piping Bellows"
  },
  {
    "id": "prod_e17",
    "category": "Expansion Joints",
    "title": "Lens Type Expansion Joint"
  },
  {
    "id": "prod_e18",
    "category": "Expansion Joints",
    "title": "Rectangular Expansion Joint"
  },
  {
    "id": "prod_e21",
    "category": "Expansion Joints",
    "title": "Cryogenic LNG / LPG Expansion Joint"
  },
  {
    "id": "prod_e26",
    "category": "Expansion Joints",
    "title": "Octagonal Profile Expansion Joint"
  },
  {
    "id": "prod_e27",
    "category": "Expansion Joints",
    "title": "Thick Wall Heavy-Duty Expansion Joint"
  },
  {
    "id": "prod_e29",
    "category": "HVAC, Ducting & Air Filtration",
    "title": "Industrial Airflow Damper"
  },
  {
    "id": "prod_e30",
    "category": "Valves, Gaskets & Steam System Products",
    "title": "Dismantling Joint"
  },
  {
    "id": "prod_e31",
    "category": "HVAC, Ducting & Air Filtration",
    "title": "MS & SS Industrial Duct Systems"
  },
  {
    "id": "prod_ts1",
    "category": "Turbine Spares",
    "title": "Carbon & Graphite Gland Sealing Rings"
  },
  {
    "id": "prod_ts2",
    "category": "Turbine Spares",
    "title": "Labyrinth Shaft Sealing Packings"
  },
  {
    "id": "prod_ts3",
    "category": "Turbine Spares",
    "title": "Babbitt Journal Bearings & Thrust Pads"
  },
  {
    "id": "prod_ts4",
    "category": "Turbine Spares",
    "title": "Emergency Stop Valves (ESV)"
  },
  {
    "id": "prod_ts5",
    "category": "Turbine Spares",
    "title": "Turbine Lube Oil Pumps & Mechanical Seals"
  },
  {
    "id": "prod_ts6",
    "category": "Turbine Spares",
    "title": "High-Purity Electrographite Sealing Rings"
  },
  {
    "id": "prod_ts7",
    "category": "Turbine Spares",
    "title": "Complete Turbine Rotor Assemblies"
  },
  {
    "id": "prod_ts8",
    "category": "Turbine Spares",
    "title": "Precision Turbine Gears & Worm Wheels"
  },
  {
    "id": "prod_ts9",
    "category": "Turbine Spares",
    "title": "Turbine Nozzles & Diaphragms"
  },
  {
    "id": "prod_ts10",
    "category": "Turbine Spares",
    "title": "Mechanical Centrifugal Speed Governors"
  },
  {
    "id": "prod_ts11",
    "category": "Turbine Spares",
    "title": "Turbine Throttle (Control) Valves"
  },
  {
    "id": "prod_r1",
    "category": "Industrial Rubber Products",
    "title": "Custom Extruded Rubber Profiles & Seals"
  },
  {
    "id": "prod_h1",
    "category": "Flexible Hoses & Assemblies",
    "title": "SS Corrugated Flexible Metal Hose Assemblies"
  },
  {
    "id": "prod_h1b",
    "category": "Flexible Hoses & Assemblies",
    "title": "SS Hose Pre-Fitted Assemblies"
  },
  {
    "id": "prod_h1c",
    "category": "Flexible Hoses & Assemblies",
    "title": "Generator & Engine Exhaust Bellows"
  },
  {
    "id": "prod_h2",
    "category": "Flexible Hoses & Assemblies",
    "title": "PTFE Lined Smooth Bore Hose Assemblies"
  },
  {
    "id": "prod_h3",
    "category": "Flexible Hoses & Assemblies",
    "title": "High-Pressure Hydraulic Rubber Hose Assemblies"
  },
  {
    "id": "prod_h4",
    "category": "Flexible Hoses & Assemblies",
    "title": "PTFE Braided Corrugated Transfer Hose"
  },
  {
    "id": "prod_h5",
    "category": "Flexible Hoses & Assemblies",
    "title": "Metallic Flexible Hose (Corrugated Core)"
  },
  {
    "id": "prod_h6",
    "category": "Flexible Hoses & Assemblies",
    "title": "Steam Hose: High Temperature Service"
  },
  {
    "id": "prod_h7",
    "category": "Flexible Hoses & Assemblies",
    "title": "Flexible Food Grade Hose"
  },
  {
    "id": "prod_f14",
    "category": "Industrial Filtration",
    "title": "Filter Bag & Support Cage Assembly"
  },
  {
    "id": "prod_ee1",
    "category": "Electronic Equipments",
    "title": "Vibration Monitoring Probes (Shinkawa-compatible)"
  },
  {
    "id": "prod_ee2",
    "category": "Electronic Equipments",
    "title": "Magnetic Pickup Sensor (Woodward)"
  },
  {
    "id": "prod_f12",
    "category": "Industrial Filtration",
    "title": "Siemens Replacement Turbine Control Oil Filters"
  },
  {
    "id": "prod_f13",
    "category": "Industrial Filtration",
    "title": "Triveni Replacement Turbine Control Oil Filters"
  },
  {
    "id": "prod_ts12",
    "category": "Turbine Spares",
    "title": "High/Low Speed Couplings for Turbines"
  },
  {
    "id": "prod_ts13",
    "category": "Turbine Spares",
    "title": "Flexible Disc Pack (MetaFlex)"
  },
  {
    "id": "prod_ts14",
    "category": "Turbine Spares",
    "title": "Boiler Sight Glass: Round / Reflex"
  },
  {
    "id": "prod_ee3",
    "category": "Electronic Equipments",
    "title": "ASCO 8210 Series Explosion-Proof Solenoid Valve"
  },
  {
    "id": "prod_ts15",
    "category": "Turbine Spares",
    "title": "Spherical White Metal Bearing: TDPS Alternator"
  },
  {
    "id": "prod_ee4",
    "category": "Electronic Equipments",
    "title": "Beacon Industrial Analog Tachometer Gauge"
  },
  {
    "id": "prod_ts16",
    "category": "Turbine Spares",
    "title": "Leaf Springs for Turbine Governors"
  },
  {
    "id": "prod_ts17",
    "category": "Turbine Spares",
    "title": "Rotor Journal Polishing Service"
  },
  {
    "id": "prod_ee5",
    "category": "Electronic Equipments",
    "title": "RTD & Sensors for Power Plants & Steam Turbines"
  },
  {
    "id": "prod_ee6",
    "category": "Electronic Equipments",
    "title": "SEMIKRON SKN240/16 Rectifier Diode"
  },
  {
    "id": "prod_ts18",
    "category": "Turbine Spares",
    "title": "Fulcrum Pins: Blade Locking / Trip Mechanism Linkage"
  },
  {
    "id": "prod_ts19",
    "category": "Turbine Spares",
    "title": "Spiral Conveyor Screw (Turbine Auxiliaries)"
  },
  {
    "id": "prod_ts20",
    "category": "Turbine Spares",
    "title": "Nylon Sleeve for Gear Coupling"
  },
  {
    "id": "prod_ts21",
    "category": "Turbine Spares",
    "title": "KTR BoWex Curved-Tooth Gear Coupling"
  },
  {
    "id": "prod_f15",
    "category": "Industrial Filtration",
    "title": "Wedge Wire Filter Element"
  },
  {
    "id": "prod_f16",
    "category": "Industrial Filtration",
    "title": "Concrete Pump Filter Element"
  },
  {
    "id": "prod_f17",
    "category": "Industrial Filtration",
    "title": "Dust Collector Filter Cartridge"
  },
  {
    "id": "prod_f18",
    "category": "Industrial Filtration",
    "title": "Pleated Dust Collector Filter Cartridge (Flange-Type)"
  },
  {
    "id": "prod_st6",
    "category": "Industrial Strainers",
    "title": "Stainless Steel Notch Wire Strainer Element"
  },
  {
    "id": "prod_f19",
    "category": "Industrial Filtration",
    "title": "Oil Vapour Extractor Filter"
  },
  {
    "id": "prod_f20",
    "category": "Industrial Filtration",
    "title": "HYDAC Replacement Filter Elements"
  },
  {
    "id": "prod_f21",
    "category": "Industrial Filtration",
    "title": "Pall Replacement Filter Elements"
  },
  {
    "id": "prod_f22",
    "category": "Industrial Filtration",
    "title": "Bhagwati Replacement Oil Filters"
  },
  {
    "id": "prod_f23",
    "category": "Industrial Filtration",
    "title": "Air Oil Separator Filter"
  },
  {
    "id": "prod_ts22",
    "category": "Turbine Spares",
    "title": "Shear Pins (Turbine Coupling)"
  },
  {
    "id": "prod_ts23",
    "category": "Turbine Spares",
    "title": "Dowty Replacement Hydraulic Oil Pumps"
  },
  {
    "id": "prod_hv1",
    "category": "Hydraulic Components",
    "title": "Directional Control Valves (All Major Makes)"
  },
  {
    "id": "prod_f_bhel",
    "category": "Industrial Filtration",
    "title": "BHEL Replacement Turbine Lube Oil Filter Elements"
  },
  {
    "id": "prod_f_htc",
    "category": "Industrial Filtration",
    "title": "HTC Replacement Turbine Filter Elements"
  },
  {
    "id": "prod_ts_blades",
    "category": "Turbine Spares",
    "title": "Steam Turbine Blades (Moving & Stationary)"
  },
  {
    "id": "prod_ts_gov_cards",
    "category": "Turbine Spares",
    "title": "Woodward Replacement Governor Cards & PCB Assemblies"
  },
  {
    "id": "prod_ts_shaft_seal_kit",
    "category": "Turbine Spares",
    "title": "Complete Shaft Seal Kit: Carbon Ring Gland Assembly"
  },
  {
    "id": "prod_ts_rebabbitting",
    "category": "Turbine Spares",
    "title": "Bearing Rebabbitting Service"
  },
  {
    "id": "prod_ts_lube_oil_cooler",
    "category": "Turbine Spares",
    "title": "Turbine Lube Oil Cooler (Shell & Tube / Plate Type)"
  },
  {
    "id": "prod_ts_pressure_instruments",
    "category": "Turbine Spares",
    "title": "Lube Oil System Pressure Instruments & Gauges"
  },
  {
    "id": "prod_gp1",
    "category": "Valves, Gaskets & Steam System Products",
    "title": "Gland Packing: Graphite, PTFE, PTFE-Graphite Braided Rope"
  },
  {
    "id": "prod_hv2",
    "category": "Hydraulic Components",
    "title": "Hydraulic Accumulators: Bladder & Piston Type"
  },
  {
    "id": "prod_srv1",
    "category": "Valves, Gaskets & Steam System Products",
    "title": "Safety Relief Valves (SRV / PSV): Spring-Loaded"
  },
  {
    "id": "prod_trap1",
    "category": "Valves, Gaskets & Steam System Products",
    "title": "Steam Trap Assemblies: Thermodynamic & Float Type"
  },
  {
    "id": "prod_gk1",
    "category": "Valves, Gaskets & Steam System Products",
    "title": "Spiral Wound Gaskets (SWG): ASME B16.20"
  },
  {
    "id": "prod_gk2",
    "category": "Valves, Gaskets & Steam System Products",
    "title": "Ring Joint Gaskets (RTJ), Oval & Octagonal: ASME B16.20"
  },
  {
    "id": "prod_f_hp1",
    "category": "Industrial Filtration",
    "title": "High-Pressure Single Cartridge Filter Housing"
  },
  {
    "id": "prod_f_mag1",
    "category": "Industrial Filtration",
    "title": "Magnetic Filter / Separator Assembly"
  },
  {
    "id": "prod_ts_prv",
    "category": "Turbine Spares",
    "title": "Pressure Reducing Valve (PRV) & PRDS Station"
  },
  {
    "id": "prod_ts_overspeed",
    "category": "Turbine Spares",
    "title": "Overspeed Trip Device & Speed Switch"
  },
  {
    "id": "prod_af1",
    "category": "HVAC, Ducting & Air Filtration",
    "title": "HVAC Pocket Bag Filter (Multi-Pocket Air Filter)"
  },
  {
    "id": "prod_af2",
    "category": "HVAC, Ducting & Air Filtration",
    "title": "Activated Carbon Vent Filter: Recirculating Air"
  },
  {
    "id": "prod_af3",
    "category": "HVAC, Ducting & Air Filtration",
    "title": "HVAC Metallic Mesh Pre-Filter"
  },
  {
    "id": "prod_af4",
    "category": "HVAC, Ducting & Air Filtration",
    "title": "Pleated Panel Air Filter"
  },
  {
    "id": "prod_af5",
    "category": "Industrial Filtration",
    "title": "Pulse-Jet Dust Collector Filter Bag / Cartridge"
  },
  {
    "id": "prod_af6",
    "category": "HVAC, Ducting & Air Filtration",
    "title": "Wound Filter Media Rolls"
  },
  {
    "id": "prod_ts_dp_switch",
    "category": "Turbine Spares",
    "title": "DP & Temperature Switches: Turbine Lube Oil Monitoring"
  },
  {
    "id": "prod_ts_labyrinth_leaf_spring",
    "category": "Turbine Spares",
    "title": "Leaf Springs for Turbine Labyrinth Gland Seals"
  },
  {
    "id": "prod_f_cenlub",
    "category": "Industrial Filtration",
    "title": "Cenlub Replacement Filter Elements"
  },
  {
    "id": "prod_f_eaton",
    "category": "Industrial Filtration",
    "title": "Eaton Replacement Filter Elements"
  },
  {
    "id": "prod_f_epe",
    "category": "Industrial Filtration",
    "title": "EPE Replacement Filter Elements"
  }
];
